title: "Computational Musicology Dashboard"
description: "K-pop vs Cantopop Analysis"
theme: jekyll-theme-cayman

nav:
  - name: Home
    link: /
  - name: Background
    link: /background
  - name: Features
    link: /features
  - name: Chroma
    link: /chroma
  - name: Loudness
    link: /loudness
  - name: Timbre
    link: /timbre
  - name: Temporal
    link: /temporal
  - name: Clustering
    link: /clustering
  - name: Contribution
    link: /contribution
