project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - music_dashboard.qmd

website:
  title: "Computational Musicology"
  description: "A Quarto website for Computational Musicology project"
  navbar:
    title: "Computational Musicology"
    right:
      - text: "Home"
        href: index.qmd
      - text: "Music Dashboard"
        href: music_dashboard.qmd
