# Quarto Website

# Define the site
website:
  title: "Computational Musicology"
  description: "A Quarto website for Computational Musicology project"
  output-dir: "_site"

# Include content
includepaths: ["./"]

# Add pages
navbar:
  title: "Computational Musicology"
  right:
    - text: "Home"
      href: index.qmd
    - text: "Music Dashboard"
      href: music_dashboard.qmd
